apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: codversion
spec:
  results:
    - name: version
      description: la nueva version de la imagen
  steps:
    - name: crear-codigo
      image: alpine
      script: |
        #!/usr/bin/env sh
        apk add --no-cache git && rm -rf /var/cache/apk/*
        codversion=$(git rev-parse --short HEAD)    
        version=$NOMBRE:$codversion
      env:
        - name: NOMBRE
          value: $(params.image-reference)  
  workspaces:
    - name: source


