apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: codversion
spec:
  results:
    - name: version
      description: la nueva version de la imagen
  params:
    - name: IMAGE
      description: la imagen a construir
      type: string
  steps:
    - name: crear-codigo
      image: alpine
      script: |
        #!/usr/bin/env sh
        apk add --no-cache git && rm -rf /var/cache/apk/*
        codversion=$(git rev-parse --short HEAD)    
        version=$IMAGE:$codversion
        echo $version | tee $(results.version.path)
      args:
        - echo
      workingDir: $(workspaces.source.path)
      env:
        - name: IMAGE
          value: $(params.IMAGE)
  workspaces:
    - name: source


