apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: codversion
spec:
  results:
    - name: version
      description: la nueva version de la imagen
  steps:
    - name: crear-codigo
      image: alpine
      script: |
        #!/usr/bin/env bash
        version=$(git rev-parse --short HEAD)        
      workingDir: $(workspaces.source.path)
      workspaces:
        - name: source
          workspace: shared-data    


